name: Test
on:
  - pull_request
  - push
jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          cache: 'npm'

      - name: Pull dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
